package dima.sweep.localcomplete.index

import dima.sweep.localcomplete.model.FileRecord
import dima.sweep.localcomplete.model.IndexedLine

object FileRecordBuilder {
    private const val maxAverageLineLength = 120
    private const val minLinesForAverageCheck = 5

    fun build(
        path: String,
        content: String,
        extension: String,
        timestamp: Long,
        sizeBytes: Long,
        maxLineLength: Int,
        activeLineNumbers: Set<Int> = emptySet(),
    ): FileRecord {
        val rawLines = content.split('\n')
        
        if (isGeneratedFile(path, content, rawLines)) {
            return FileRecord(
                absolutePath = path,
                extension = extension,
                lastIndexedTimestamp = timestamp,
                lines = emptyList(),
                sizeBytes = sizeBytes,
            )
        }

        val indexedLines = rawLines.mapIndexedNotNull { index, rawLine ->
            val currentLineNumber = index + 1
            if (currentLineNumber in activeLineNumbers) return@mapIndexedNotNull null

            val originalLine = rawLine.removeSuffix("\r")
            val normalizedContent = originalLine.trim()
            if (LineFilter.shouldSkip(normalizedContent, originalLine.length, maxLineLength)) {
                return@mapIndexedNotNull null
            }

            IndexedLine(
                normalizedContent = normalizedContent,
                originalContent = originalLine,
                leadingWhitespace = originalLine.takeWhile { it == ' ' || it == '\t' },
                sourceFilePath = path,
                lineNumber = currentLineNumber,
                prefixContextHashes = ContextHash.prefixHashesForLine(rawLines, index),
                suffixContextHashes = ContextHash.suffixHashesForLine(rawLines, index),
            )
        }

        return FileRecord(
            absolutePath = path,
            extension = extension,
            lastIndexedTimestamp = timestamp,
            lines = indexedLines,
            sizeBytes = sizeBytes,
        )
    }

    private fun isGeneratedFile(path: String, content: String, rawLines: List<String>): Boolean {
        if (isGeneratedPath(path)) return true
        if (containsGeneratedAnnotation(content)) return true
        if (hasExcessiveAverageLineLength(rawLines)) return true
        return false
    }

    private fun isGeneratedPath(path: String): Boolean {
        val generatedPathPatterns = listOf(
            "/build/", "/target/", "/dist/", "/out/", "/generated/",
            "/node_modules/", "/.gradle/", "/.idea/",
            "build.gradle.kts", "pom.xml", "package-lock.json",
            ".min.js", ".min.css", ".generated.", ".pb.", ".proto.",
        )
        return generatedPathPatterns.any { path.contains(it, ignoreCase = true) }
    }

    private fun containsGeneratedAnnotation(content: String): Boolean {
        val header = content.lineSequence().take(10).joinToString("\n")
        val generatedMarkers = listOf(
            "@Generated",
            "@generated",
            "// Generated by",
            "/* Generated by",
            "// DO NOT EDIT",
            "/* DO NOT EDIT",
            "<auto-generated>",
            "This file was automatically generated",
            "This source file was auto-generated",
        )
        return generatedMarkers.any { header.contains(it, ignoreCase = true) }
    }

    private fun hasExcessiveAverageLineLength(rawLines: List<String>): Boolean {
        if (rawLines.size < minLinesForAverageCheck) return false
        
        val totalLength = rawLines.sumOf { it.length }
        val averageLength = totalLength.toDouble() / rawLines.size
        
        return averageLength > maxAverageLineLength
    }
}